### ISSUE TITLE
How to regenerate a unique field?

### ISSUE THREAD

**Issue by FrankFang** [eventtus/uniqueness#2]

**Comment by ahmgeek** [comment]
hey @FrankFang, regenerate in a sense of what?
if you added `has_unique_field :uid` in a `User` model, you could generate a new one like this:
`User.new.uniqueness_generate`

**Comment by FrankFang** [comment]
Thanks

**Comment by ahmgeek** [comment]
@FrankFang Just a quick reminder, I've added the interface for such feature  for an ease use.
you can use it directly like: `Uniqueness.generate(type: :human)` for instance.
Make sure to update your gem first if you use it of course.
