### ISSUE TITLE
Increase randomness

### ISSUE THREAD

**Issue by eliotsykes** [eventtus/uniqueness#9]
Consider replacing `rand` use with `SecureRandom` to increase randomness for the benefit of applications relying on the uniqueness gem for security-related purposes.

Note Rails' `has_secure_token` uses `SecureRandom` for generation: 

https://github.com/rails/rails/blob/15ef55efb591e5379486ccf53dd3e13f416564f6/activerecord/lib/active_record/secure_token.rb#L28-L37

https://github.com/rails/rails/blob/cfb1e4dfd8813d3d5c75a15a750b3c53eebdea65/activesupport/lib/active_support/core_ext/securerandom.rb#L18-L24

**Comment by amrrbakry** [comment]
Hi @eliotsykes, thank you so much for raising this issue. We'll make sure to fix this in our next release. :+1: :+1:
